name: CI - Build & Push Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_USER: ${{ secrets.GH_USER }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Build binary
        run: go build -o app ./cmd

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u $GH_USER --password-stdin

      - name: Build & Push Docker image
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          IMAGE_NAME=ghcr.io/$GH_USER/go-app:$IMAGE_TAG
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Helm values
        run: |
          git clone https://github.com/$GH_USER/go-app-helm.git
          cd go-app-helm
          yq -i '.image.tag = "${{ env.IMAGE_TAG }}"' values.yaml
          git config user.name github-actions
          git config user.email actions@github.com
          git commit -am "Update image tag to ${{ env.IMAGE_TAG }}"
          git push origin main
